---
- hosts: all
  become: yes
  tasks:
    - name: Install JDK 17 on CentOS
      yum:
        name: java-17-openjdk-devel
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install JDK 17 on Debian
      apt:
        name: openjdk-17-jdk
        state: latest
      when: ansible_os_family == "Debian"
      become: yes
      become_method: sudo

    - name: Copy Jar to server
      copy:
        src: ../target/SmartHome-1.0-SNAPSHOT-jar-with-dependencies.jar
        dest: smart-home.jar

    - name: Copy json configuration to server
      copy:
        src: ../src/SmartHome.json
        dest: SmartHome.json

    - name: Запуск JAR
      shell: java -jar smart-home.jar