---
- hosts: all
  become: yes
  tasks:
    - name: Install JDK 17 on CentOS
      yum:
        name: java-11-openjdk-devel
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install JDK 11 on Debian
      apt:
        name: openjdk-11-jdk
        state: latest
      when: ansible_os_family == "Debian"

    - name: Copy Jar to server
      copy:
        src: ../target/SmartHome-1.0-SNAPSHOT-jar-with-dependencies.jar
        dest: SmartHome.jar
        remote_src: no

    - name: Copy json configuration to server
      copy:
        src: ../src/ru/sbt/mipt/oop/SmartHome.json
        dest: SmartHome.json
        remote_src: no

    - name: Запуск JAR
      shell: java -jar SmartHome.jar